DESC emp;
SELECT * FROM emp;
SELECT EMPNO , ENAME FROM emp;
SELECT EMPNO as NUM , ENAME as NAME FROM emp;
SELECT ENAME FROM emp WHERE DEPTNO =20 ;
SELECT ENAME FROM emp WHERE DEPTNO =10 OR DEPTNO=20
SELECT ENAME FROM emp WHERE HIREDATE > '01-JAN-82'
SELECT ENAME FROM emp WHERE HIREDATE > '01-JAN-82' AND DEPTNO=10
SELECT ENAME FROM emp WHERE COMM IS NULL
SELECT ENAME FROM emp WHERE COMM =0
SELECT ENAME FROM emp WHERE DEPTNO = 30
SELECT ENAME,EMPNO, DEPTNO FROM EMP WHERE DEPTNO >= 20
SELECT ENAME FROM EMP WHERE COMM > sal *(60/100)
SELECT ENAME, JOB, SAL FROM EMP WHERE DEPTNO = 20 AND SAL > 2000
SELECT ENAME, EMPNO FROM EMP WHERE DEPTNO = 30 AND SAL >= 1500
SELECT ENAME, EMPNO FROM EMP WHERE JOB = 'manager' OR JOB = 'PRESIDENT'
SELECT ENAME, EMPNO, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO FROM EMP WHERE DEPTNO = 10 AND JOB = 'MANAGER' OR JOB = 'CLERK'
SELECT * FROM EMP WHERE JOB ='MANAGER' OR (JOB = 'CLERK') AND DEPTNO=10
SELECT * FROM EMP WHERE (JOB= 'MANAGER' AND DEPTNO=10) OR (JOB = 'CLERK' AND DEPTNO=20)
SELECT * FROM EMP WHERE (JOB= 'MANAGER' AND DEPTNO=10) OR (JOB= 'CLERK' AND DEPTNO=20) OR(
JOB!= 'MANAGER' OR JOB!= 'CLERK') AND ( SAL >= 2000);
SELECT SAL FROM EMP ORDER BY SAL DESC;
SELECT ENAME, SAL FROM EMP ORDER BY SAL DESC;