CREATE TABLE EMPLOYEE (
    ENAME      VARCHAR2(30) NOT NULL,                       
    ESRNO      NUMBER(6) PRIMARY KEY,                       
    BDATE      DATE CHECK (BDATE BETWEEN DATE '1955-01-01' AND DATE '1979-12-31'),
    ADDRESS    VARCHAR2(50),
    SEX        CHAR(1) DEFAULT 'M' CHECK (SEX IN ('M','F')),
    SALARY     NUMBER CHECK (SALARY BETWEEN 20000 AND 40000),
    MGRSRNO    NUMBER,
    DNO        NUMBER,

    CONSTRAINT fk_mgr FOREIGN KEY (MGRSRNO) REFERENCES EMPLOYEE(ESRNO)
);
DESCRIBE EMPLOYEE

CREATE TABLE DEPARTMENT (
    DNAME      VARCHAR2(20) 
        CHECK (DNAME IN ('RESEARCH','ADMIN','PROJECT','ACADEMIC')),
    DNUMBER    NUMBER PRIMARY KEY CHECK (DNUMBER > 0 AND DNUMBER <= 4),
    MGRSRNO    NUMBER,
    MGRSTARTD  DATE,

    CONSTRAINT fk_dept_mgr FOREIGN KEY (MGRSRNO) REFERENCES EMPLOYEE(ESRNO)
);
DESCRIBE DEPARTMENT

CREATE TABLE DEPT_LOCATIONS (
    DNUMBER    NUMBER CHECK (DNUMBER > 0 AND DNUMBER <= 4),
    DLOCATION  VARCHAR2(20)
        CHECK (DLOCATION IN ('SINGAPORE','INDIA','QUUENSLAND','LONDON')),

    CONSTRAINT fk_deptloc_dnum FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER)
);
DESCRIBE DEPT_LOCATIONS

CREATE TABLE PROJECT (
    PNAME      VARCHAR2(30)
        CHECK (PNAME IN ('NETWORKING','BIO INFORMATICS','LINUX')),
    PNUMBER    NUMBER PRIMARY KEY,
    PLOCATION  VARCHAR2(30)
        CHECK (PLOCATION IN ('KOREA','SOUTH AFRICA','INDIA')),
    DNUM       NUMBER,

    CONSTRAINT fk_proj_dnum FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUMBER)
);
DESCRIBE PROJECT

CREATE TABLE WORKS_ON (
    ESRNO   NUMBER CHECK (ESRNO > 0),
    PNO     NUMBER CHECK (PNO > 0),
    HOURS   NUMBER CHECK (HOURS > 0),

    CONSTRAINT fk_works_emp FOREIGN KEY (ESRNO) REFERENCES EMPLOYEE(ESRNO),
    CONSTRAINT fk_works_proj FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER)
);
DESCRIBE WORKS_ON

INSERT INTO EMPLOYEE VALUES ('AJIT NAYAK',133100,DATE '1955-04-25','73 BOSTON','M',35000,NULL,1),
('SATYA',495823,DATE '1966-07-17','26 FINE OAK','M',32770,133100,4),
('AJIT BEHERA',315152,DATE '1971-07-09','10 KALINGA','M',32802,133100,3),
('UMASHANKAR',216852,DATE '1967-07-17','26 FINE OAK','M',32770,133100,2),
('BHAGWAT',215152,DATE '1971-03-23','55 FLORIDA','M',32802,216852,2),
('MEENAKSHI',334548,DATE '1979-04-25','73 BRIKLY','F',25125,315152,3),
('JASWASI',215485,DATE '1979-08-12','17 BOSTON','M',20500,495823,4),
('NIHAR NAYAK',334524,DATE '1966-12-17','73 DALLAS','M',29105,315152,3),
('DEBASMITA',295485,DATE '1970-04-16','1 QUEENS LAND','F',20500,216852,2);

SELECT * FROM EMPLOYEE

INSERT INTO DEPARTMENT VALUES ('RESEARCH',4,495823,DATE '1999-04-20'),
('ADMIN',1,133100,DATE '1988-01-06'),
('PROJECT',2,216852,DATE '1999-07-17'),
('ACADEMIC',3,315152,DATE '1989-12-20');

SELECT * FROM DEPARTMENT

INSERT INTO PROJECT VALUES ('NETWORKING',11,'KOREA',4),
('BIO INFORMATICS',19,'SOUTH AFRICA',3),
('LINUX',17,'INDIA',2);

SELECT * FROM PROJECT

INSERT INTO DEPT_LOCATIONS VALUES (2,'SINGAPORE'),
(1,'INDIA'),
(4,'QUUENSLAND'),
(3,'LONDON');

SELECT * FROM DEPT_LOCATIONS

INSERT INTO WORKS_ON VALUES (495823,11,5.27),
(215152,17,2.32),
(495823,11,4.15),
(315152,19,1.25),
(334548,19,3.28),
(215485,17,1.25),
(295485,17,5.35),
(334548,19,2.54),
(295485,17,7.20),
(216852,17,2.41),
(334524,19,3.24),
(295485,17,1.36),
(495823,11,2.36),
(215152,17,1.25),
(495823,11,3.14),
(315152,19,2.05),
(334548,19,2.50),
(215485,17,2.34);

SELECT * FROM WORKS_ON

SELECT ENAME,ADDRESS,DNO,DNAME from EMPLOYEE E,DEPARTMENT D where E.DNO = D.DNUMBER;
SELECT e.ENAME, d.DNAME, d.MGRSTARTD, e.SALARY FROM EMPLOYEE e, DEPARTMENT d WHERE d.MGRSRNO = e.ESRNO;
SELECT d.DNAME, d.DNUMBER, dl.DLOCATION FROM DEPARTMENT d, DEPT_LOCATIONS dl WHERE d.DNUMBER = dl.DNUMBER;
SELECT p.PNAME, p.PNUMBER, p.PLOCATION, SUM(w.HOURS) FROM PROJECT p, WORKS_ON w WHERE p.PNUMBER = w.PNO GROUP BY p.PNAME, p.PNUMBER, p.PLOCATION;
SELECT e.* FROM EMPLOYEE e, DEPARTMENT d WHERE e.DNO = d.DNUMBER AND d.DNAME = 'ACADEMIC';
SELECT e.* FROM EMPLOYEE e, DEPARTMENT d WHERE d.MGRSRNO = e.ESRNO AND d.MGRSTARTD = DATE '1999-07-17';
SELECT e.* FROM EMPLOYEE e, WORKS_ON w, PROJECT p WHERE e.ESRNO = w.ESRNO AND w.PNO = p.PNUMBER AND p.PNAME = 'BIO INFORMATICS';
SELECT e.* FROM EMPLOYEE e, WORKS_ON w, PROJECT p WHERE e.ESRNO = w.ESRNO AND w.PNO = p.PNUMBER AND p.PNAME = 'LINUX';
SELECT p.PLOCATION FROM EMPLOYEE e, WORKS_ON w, PROJECT p WHERE e.ESRNO = w.ESRNO AND w.PNO = p.PNUMBER AND e.ENAME = 'SATYA';
SELECT e.* FROM EMPLOYEE e, WORKS_ON w, PROJECT p WHERE e.ESRNO = w.ESRNO AND w.PNO = p.PNUMBER AND p.PLOCATION = 'SOUTH AFRICA';
SELECT SUM(w.HOURS) FROM WORKS_ON w, PROJECT p WHERE w.PNO = p.PNUMBER AND p.PNAME = 'NETWORKING';
SELECT e.* FROM EMPLOYEE e, DEPT_LOCATIONS dl WHERE e.DNO = dl.DNUMBER AND dl.DLOCATION = 'INDIA';
SELECT e.ENAME, SUM(w.HOURS) FROM EMPLOYEE e, WORKS_ON w WHERE e.ESRNO = w.ESRNO GROUP BY e.ENAME;
SELECT SUM(w.HOURS) FROM WORKS_ON w, PROJECT p WHERE w.PNO = p.PNUMBER AND p.PNAME = 'LINUX';
SELECT e.* FROM EMPLOYEE e, WORKS_ON w, PROJECT p WHERE e.ESRNO = w.ESRNO AND w.PNO = p.PNUMBER AND p.PLOCATION = 'INDIA';
SELECT e.ESRNO, e.ENAME, d.DNUMBER, d.DNAME, p.PNAME, w.HOURS FROM EMPLOYEE e, DEPARTMENT d, WORKS_ON w, PROJECT p WHERE e.DNO = d.DNUMBER AND e.ESRNO = w.ESRNO AND w.PNO = p.PNUMBER;
SELECT e.ENAME FROM EMPLOYEE e, DEPARTMENT d WHERE e.DNO = d.DNUMBER AND d.DNAME = 'RESEARCH';
SELECT e.ENAME, w.HOURS FROM EMPLOYEE e, WORKS_ON w WHERE e.ESRNO = w.ESRNO AND w.HOURS > 5;
SELECT e.* FROM EMPLOYEE e, DEPARTMENT d WHERE e.DNO = d.DNUMBER AND d.DNAME <> 'ACADEMIC';
SELECT SUM(w.HOURS) FROM EMPLOYEE e, WORKS_ON w WHERE e.ESRNO = w.ESRNO AND e.SEX = 'F';
SELECT e.ENAME, SUM(w.HOURS) FROM EMPLOYEE e, WORKS_ON w, DEPARTMENT d WHERE d.MGRSRNO = e.ESRNO AND e.ESRNO = w.ESRNO GROUP BY e.ENAME;
SELECT e.*, d.*, w.*, p.* FROM EMPLOYEE e, DEPARTMENT d, WORKS_ON w, PROJECT p WHERE e.DNO = d.DNUMBER AND e.ESRNO = w.ESRNO AND w.PNO = p.PNUMBER AND e.ENAME = 'MEENAKSHI';
SELECT e.ENAME FROM EMPLOYEE e, WORKS_ON w WHERE e.ESRNO = w.ESRNO AND w.PNO = 19;
SELECT e.ENAME, w.HOURS FROM EMPLOYEE e, WORKS_ON w WHERE e.ESRNO = w.ESRNO AND e.ADDRESS LIKE '%BOSTON%';
SELECT p.PNAME, p.PLOCATION, w.ESRNO, SUM(w.HOURS) FROM PROJECT p, WORKS_ON w WHERE p.PNUMBER = w.PNO GROUP BY p.PNAME, p.PLOCATION, w.ESRNO;
SELECT p.PNAME, SUM(w.HOURS) FROM PROJECT p, WORKS_ON w WHERE p.PNUMBER = w.PNO GROUP BY p.PNAME;
SELECT e.*, w.* FROM EMPLOYEE e, WORKS_ON w WHERE e.ESRNO = w.ESRNO(+) AND e.ENAME = 'AJIT NAYAK';
SELECT e.*, d.*, w.*, p.* FROM EMPLOYEE e, DEPARTMENT d, WORKS_ON w, PROJECT p WHERE e.DNO = d.DNUMBER AND e.ESRNO = w.ESRNO AND w.PNO = p.PNUMBER;

SELECT e.ENAME, e.ADDRESS, e.DNO, d.DNAME
FROM EMPLOYEE e
JOIN DEPARTMENT d ON e.DNO = d.DNUMBER;

SELECT e.ENAME AS MANAGER_NAME, d.DNAME, d.MGRSTARTD, e.SALARY
FROM DEPARTMENT d
JOIN EMPLOYEE e ON d.MGRSRNO = e.ESRNO;

SELECT d.DNAME, d.DNUMBER, dl.DLOCATION
FROM DEPARTMENT d
JOIN DEPT_LOCATIONS dl ON d.DNUMBER = dl.DNUMBER;

SELECT p.PNAME, p.PNUMBER, p.PLOCATION, SUM(w.HOURS) AS TOTAL_HOURS
FROM PROJECT p
LEFT JOIN WORKS_ON w ON p.PNUMBER = w.PNO
GROUP BY p.PNAME, p.PNUMBER, p.PLOCATION;

SELECT e.*
FROM EMPLOYEE e
JOIN DEPARTMENT d ON e.DNO = d.DNUMBER
WHERE d.DNAME = 'ACADEMIC';

SELECT e.*
FROM EMPLOYEE e
JOIN DEPARTMENT d ON d.MGRSRNO = e.ESRNO
WHERE d.MGRSTARTD = DATE '1999-07-17';

SELECT e.*
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
JOIN PROJECT p ON w.PNO = p.PNUMBER
WHERE p.PNAME = 'BIO INFORMATICS';

SELECT e.*
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
JOIN PROJECT p ON w.PNO = p.PNUMBER
WHERE p.PNAME = 'LINUX';

SELECT p.PLOCATION
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
JOIN PROJECT p ON w.PNO = p.PNUMBER
WHERE e.ENAME = 'SATYA';

SELECT e.*
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
JOIN PROJECT p ON w.PNO = p.PNUMBER
WHERE p.PLOCATION = 'SOUTH AFRICA';

SELECT SUM(w.HOURS) AS TOTAL_HOURS
FROM WORKS_ON w
JOIN PROJECT p ON w.PNO = p.PNUMBER
WHERE p.PNAME = 'NETWORKING';

SELECT e.*
FROM EMPLOYEE e
JOIN DEPT_LOCATIONS dl ON e.DNO = dl.DNUMBER
WHERE dl.DLOCATION = 'INDIA';

SELECT e.ENAME, SUM(w.HOURS) AS TOTAL_HOURS
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
GROUP BY e.ENAME;

SELECT SUM(w.HOURS)
FROM WORKS_ON w
JOIN PROJECT p ON w.PNO = p.PNUMBER
WHERE p.PNAME = 'LINUX';

SELECT e.*
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
JOIN PROJECT p ON w.PNO = p.PNUMBER
WHERE p.PLOCATION = 'INDIA';

SELECT e.ESRNO, e.ENAME, d.DNUMBER, d.DNAME, p.PNAME, w.HOURS
FROM EMPLOYEE e
JOIN DEPARTMENT d ON e.DNO = d.DNUMBER
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
JOIN PROJECT p ON w.PNO = p.PNUMBER;

SELECT e.ENAME
FROM EMPLOYEE e
JOIN DEPARTMENT d ON e.DNO = d.DNUMBER
WHERE d.DNAME = 'RESEARCH';

SELECT e.*, w.HOURS
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
WHERE w.HOURS > 5;

SELECT e.*
FROM EMPLOYEE e
JOIN DEPARTMENT d ON e.DNO = d.DNUMBER
WHERE d.DNAME <> 'ACADEMIC';

SELECT SUM(w.HOURS) AS TOTAL_FEMALE_HOURS
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
WHERE e.SEX = 'F';

SELECT e.ENAME AS MANAGER_NAME, SUM(w.HOURS) AS TOTAL_HOURS
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
JOIN DEPARTMENT d ON e.ESRNO = d.MGRSRNO
GROUP BY e.ENAME;

SELECT e.*, d.*, w.*, p.*
FROM EMPLOYEE e
LEFT JOIN DEPARTMENT d ON e.DNO = d.DNUMBER
LEFT JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
LEFT JOIN PROJECT p ON w.PNO = p.PNUMBER
WHERE e.ENAME = 'MEENAKSHI';

SELECT e.ENAME
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
WHERE w.PNO = 19;

SELECT e.ENAME, w.HOURS
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
WHERE e.ADDRESS LIKE '%BOSTON%';

SELECT p.PNAME, p.PLOCATION, w.ESRNO, SUM(w.HOURS) AS TOTAL_HOURS
FROM PROJECT p
JOIN WORKS_ON w ON p.PNUMBER = w.PNO
GROUP BY p.PNAME, p.PLOCATION, w.ESRNO;

SELECT p.PNAME, SUM(w.HOURS) AS TOTAL_HOURS
FROM PROJECT p
JOIN WORKS_ON w ON p.PNUMBER = w.PNO
GROUP BY p.PNAME;

SELECT d.DNAME
FROM DEPARTMENT d
JOIN PROJECT p ON d.DNUMBER = p.DNUM
JOIN WORKS_ON w ON p.PNUMBER = w.PNO
GROUP BY d.DNAME
ORDER BY SUM(w.HOURS) DESC
FETCH FIRST 1 ROW ONLY;

SELECT d.DNAME
FROM DEPARTMENT d
JOIN PROJECT p ON d.DNUMBER = p.DNUM
JOIN WORKS_ON w ON p.PNUMBER = w.PNO
GROUP BY d.DNAME
ORDER BY SUM(w.HOURS) DESC
FETCH FIRST 1 ROW ONLY;

SELECT e.*, w.*
FROM EMPLOYEE e
LEFT JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
WHERE e.ENAME = 'AJIT NAYAK';

SELECT e.*, d.*, w.*, p.*
FROM EMPLOYEE e
LEFT JOIN DEPARTMENT d ON e.DNO = d.DNUMBER
LEFT JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
LEFT JOIN PROJECT p ON w.PNO = p.PNUMBER;