select * FROM EMP
select * FROM DEPT
select * FROM EMP WHERE JOB = 'CLERK'
SELECT * FROM EMP WHERE EMPNO = 7788
SELECT * FROM EMP WHERE COMM < SAL
SELECT * FROM EMP WHERE SAL BETWEEN 1000 AND 2700
SELECT * FROM EMP WHERE EMPNO IN (7369, 7499, 7521);
SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE ENAME LIKE 'S%';
SELECT * FROM EMP WHERE ENAME LIKE '__O%';
SELECT * FROM EMP WHERE ENAME LIKE '____';
SELECT * FROM EMP WHERE ENAME LIKE '%A%';
SELECT * FROM EMP WHERE ENAME LIKE '_A%';
SELECT * FROM EMP WHERE ENAME LIKE '%A';
SELECT * FROM EMP WHERE JOB LIKE 'MANAGER';
SELECT * FROM EMP WHERE SAL NOT BETWEEN 1000 AND 2700;
SELECT * FROM EMP WHERE COMM IS NOT NULL;
SELECT * FROM EMP WHERE ENAME NOT LIKE 'S%';
SELECT * FROM EMP WHERE ENAME NOT LIKE '__O%';
SELECT * FROM EMP WHERE ENAME NOT LIKE '____';
SELECT * FROM EMP WHERE JOB NOT LIKE 'MANAGER';
SELECT * FROM EMP WHERE ENAME NOT LIKE '%A%';
SELECT * FROM EMP WHERE ENAME NOT LIKE '_A%';
SELECT * FROM EMP WHERE ENAME NOT LIKE '%A';
SELECT * FROM EMP WHERE EMPNO NOT IN (7369, 7499, 7521);
SELECT ENAME, SAL + COMM AS TOTAL_EARNINGS FROM EMP;
SELECT ENAME, SAL and COMM AS TOTAL_EARNINGS FROM EMP;
SELECT ENAME, SAL + NVL(NULLIF(COMM, 0), 100) AS TOTAL_EARNINGS FROM EMP;
SELECT * FROM EMP WHERE SAL > 2000 AND JOB = 'MANAGER';
SELECT * FROM EMP WHERE SAL > 3000 OR JOB = 'MANAGER';
SELECT * FROM EMP WHERE NOT (SAL > 3000 OR JOB = 'MANAGER');
SELECT * FROM EMP WHERE DEPTNO = 20 AND SAL <= 2000;
SELECT * FROM EMP WHERE DEPTNO = 30 OR SAL >= 3000;
SELECT * FROM EMP WHERE NOT (DEPTNO = 20 AND SAL <= 2000);
SELECT * FROM EMP WHERE NOT (DEPTNO = 30 OR SAL >= 3000);
SELECT * FROM EMP WHERE (SAL > 2000 AND JOB = 'MANAGER') OR DEPTNO = 10;
SELECT * FROM EMP WHERE DEPTNO = 20 AND (SAL <= 2000 OR JOB = 'ANALYST');
SELECT * FROM EMP WHERE NOT (SAL > 2000 AND JOB = 'MANAGER');
SELECT * FROM EMP WHERE NOT (DEPTNO = 20 AND (SAL <= 2000 OR JOB = 'ANALYST'));
SELECT * FROM EMP WHERE SAL > 2000 AND JOB IN ('MANAGER', 'CLERK');
SELECT * FROM EMP WHERE DEPTNO = 20 OR JOB IN ('ANALYST', 'SALESMAN');
SELECT ENAME FROM EMP WHERE ENAME LIKE '_ARD' OR ENAME LIKE '_ORD';
SELECT ENAME || '_' || JOB AS EMP_JOB FROM EMP WHERE ENAME IN ('SMITH', 'ADAMS') AND JOB LIKE 'CLERK';
SELECT '%' || ENAME || '_' || JOB AS EMP_JOB FROM EMP WHERE (ENAME = 'ALLEN' AND JOB = 'SALESMAN') OR (ENAME = 'ADAMS' AND JOB = 'CLERK');
SELECT * FROM EMP WHERE (SAL > 2000 AND JOB = 'MANAGER') OR (DEPTNO = 10 AND COMM IS NOT NULL);